env:
    PYTHON_VERSION: '3.10'

name: Sandbox/playground

on:
    workflow_dispatch:
        inputs:

jobs:
    win:
        runs-on: windows-2019

        steps:
            - uses: actions/setup-python@v2
              with:
                python-version: ${{ env.PYTHON_VERSION }}
                architecture: 'x64'

            - name:
              shell: bash
              run: |
                ls -l $pythonLocation

    mac:
        runs-on: macos-11

        steps:
            - uses: actions/setup-python@v2
              with:
                python-version: ${{ env.PYTHON_VERSION }}
                architecture: 'x64'

            - name:
              shell: bash
              run: |
                zip --help
                ls -l $pythonLocation/lib
                
            - name: Create python files in output dir
              shell: bash
              run: |
                pythonPath=${{ env.pythonLocation }}
                ver=${{ env.PYTHON_VERSION }}
                zip -r python${ver//./}.zip \
                    $pythonPath/lib/encodings
                    $pythonPath/lib/_collections_abc.py \
                    $pythonPath/lib/_sitebuiltins.py \
                    $pythonPath/lib/abc.py \
                    $pythonPath/lib/codecs.py \
                    $pythonPath/lib/genericpath.py \
                    $pythonPath/lib/io.py \
                    $pythonPath/lib/ntpath.py \
                    $pythonPath/lib/os.py \
                    $pythonPath/lib/site.py \
                    $pythonPath/lib/stat.py
                cp $pythonPath/libpython${{ env.PYTHON_VERSION }}.dylib .


    linux:
        runs-on: ubuntu-20.04

        steps:
            - uses: actions/setup-python@v2
              with:
                python-version: ${{ env.PYTHON_VERSION }}
                architecture: 'x64'

            - name:
              shell: bash
              run: |
                ls -l $pythonLocation/lib

            - name: Create python files in output dir
              shell: bash
              run: |
                pythonPath=${{ env.pythonLocation }}
                ver=${{ env.PYTHON_VERSION }}
                zip -r python${ver//./}.zip
                    $pythonPath/lib/encodings \
                    $pythonPath/lib/_collections_abc.py \
                    $pythonPath/lib/_sitebuiltins.py \
                    $pythonPath/lib/abc.py \
                    $pythonPath/lib/codecs.py \
                    $pythonPath/lib/genericpath.py \
                    $pythonPath/lib/io.py \
                    $pythonPath/lib/ntpath.py \
                    $pythonPath/lib/os.py \
                    $pythonPath/lib/site.py \
                    $pythonPath/lib/stat.py
                cp $pythonPath/libpython${{ env.PYTHON_VERSION }}.so* .
