env:
    PYTHON_VERSION: '3.10'

name: Sandbox/playground

on:
    workflow_dispatch:
        inputs:

jobs:
    win:
        runs-on: windows-2019

        steps:
            - uses: actions/setup-python@v2
              with:
                python-version: ${{ env.PYTHON_VERSION }}
                architecture: 'x64'

            - name:
              shell: bash
              run: |
                ls -l $pythonLocation

    mac:
        runs-on: macos-11

        steps:
            - uses: actions/setup-python@v2
              with:
                python-version: ${{ env.PYTHON_VERSION }}
                architecture: 'x64'

            - name:
              shell: bash
              run: |
                zip --help
                ls -l $pythonLocation/lib

    linux:
        runs-on: ubuntu-20.04

        steps:
            - uses: actions/setup-python@v2
              with:
                python-version: ${{ env.PYTHON_VERSION }}
                architecture: 'x64'

            - name:
              shell: bash
              run: |
                ls -l $pythonLocation/lib
