env:
    PYTHON_VERSION: '3.9'
    winPythonLocation: 'C:/hostedtoolcache/windows/python/3.9.7/x64'

name: Sandbox/playground

on:
    workflow_dispatch:
        inputs:

jobs:
    win:
        runs-on: windows-2019

        steps:
            - uses: actions/setup-python@v2
              with:
                python-version: ${{ env.PYTHON_VERSION }}
                architecture: 'x64'

            - name:
              shell: bash
              run: |
                ls -l $pythonLocation/lib
                ls -l $pythonLocation/lib/python3.9

    mac:
        runs-on: macos-11

        steps:
            - uses: actions/setup-python@v2
              with:
                python-version: ${{ env.PYTHON_VERSION }}
                architecture: 'x64'

            - name:
              shell: bash
              run: |
                ls -l $pythonLocation/lib
                ls -l $pythonLocation/lib/python3.9

    linux:
        runs-on: ubuntu-20.04

        steps:
            - uses: actions/setup-python@v2
              with:
                python-version: ${{ env.PYTHON_VERSION }}
                architecture: 'x64'

            - name:
              shell: bash
              run: |
                ls -l $pythonLocation/lib
                ls -l $pythonLocation/lib/python3.9
